

# Mostra a mensagem de erro no corpo da resposta (ex.: "Produto nao encontrado com id 2")
spring.web.error.include-message=always

spring.application.name=sorveteria

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
